from os.path import abspath

EXTENSION_PATH: str = f"{"/".join(__file__.split("/")[:-1])}/"
if len(EXTENSION_PATH) <= 1:
    EXTENSION_PATH = "."
EXTENSION_PATH = abspath(EXTENSION_PATH)
if EXTENSION_PATH[-1] != "/":
    EXTENSION_PATH += "/"

# Navigation
# https://developer.valvesoftware.com/wiki/Steam_browser_protocol
# TODO: Add more friends actions
# TODO: Add groups actions
STEAM_NAVIGATIONS: list[str] = [
    "AddNonSteamGame",
    "advertise/%g",
    "appnews/%g",
    "backup/%g",
    "browsemedia",
    "cdkeys/%g",
    "checksysreqs/%g",
    "controllerconfig/%g",
    "defrag/%g",
    "exit",
    "friends",
    "friends/players",
    "friends/settings/hideoffline",
    "friends/settings/showavatars",
    "friends/settings/sortbyname",
    "friends/status/away",
    "friends/status/busy",
    "friends/status/invisible",
    "friends/status/trade",
    "friends/status/play",
    "friends/status/offline",
    "friends/status/online",
    "flushconfig",
    "forceinputappid/%g",
    "gameproperties/%g",
    "guestpasses",
    "musicplayer/play",
    "musicplayer/pause",
    "musicplayer/toggleplaypause",
    "musicplayer/playprevious",
    "musicplayer/playnext",
    "musicplayer/togglemute",
    "musicplayer/increasevolume",
    "musicplayer/decreasevolume",
    "musicplayer/toggleplayingrepeatstatus",
    "musicplayer/toggleplayingshuffled",
    "open/activateproduct",
    "open/bigpicture",
    "open/console",
    "open/downloads",
    "open/friends",
    "open/games",
    "open/games/details",
    "open/games/grid",
    "open/games/list",
    "open/largegameslist",
    "open/minigameslist",
    "open/main",
    "open/music",
    "open/musicplayer",
    "open/mymedia",
    "open/news",
    "open/registerproduct",
    "open/screenshots/%g",
    "open/servers",
    "open/settings",
    "open/tools",
    "settings/account",
    "settings/friends",
    "settings/interface",
    "settings/ingame",
    "settings/downloads",
    "settings/voice",
    "stopstreaming",
    "store",
    "store/%g",
    "uninstall/%g",
    "UpdateFirmware",
    "updatenews/%g",
    "url/CommentNotifications",
    "url/CommunityFriendsThatPlay/%g",
    "url/CommunityHome",
    "url/CommunityInventory",
    "url/CommunitySearch",
    "url/DownloadsSupportInfo",
    "url/FamilySharing",
    "url/GameHub/%g",
    "url/LeaveGroupPage",
    "url/LegalInformation",
    "url/MyHelpRequests",
    "url/ParentalSetup",
    "url/PrivacyPolicy",
    "url/SSA",
    "url/SteamIDControlPage",
    "url/SteamIDEditPage",
    "url/SteamIDFriendsPage",
    "url/SteamIDMyProfile",
    "url/SteamWorkshop",
    "url/SteamWorkshopPage/%g",
    "url/SteamGreenlight",
    "url/Store",
    "url/StoreAccount",
    "url/StoreAppPage/%g",
    "url/StoreDLCPage/%g",
    "url/StoreCart",
    "url/Storefront",
    "url/StoreFrontPage",
    "url/SupportFrontPage",
    "validate/%g",
]

DEFAULT_LANGUAGE: str = "en-GB"
